development:
  adapter: mysql2
  database: db_name_dev
  username: root
  password: ~
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: db_name_test
  username: root
  password: ~
  host: localhost
  socket: /tmp/mysql.sock
